# Generated by Django 4.0.1 on 2022-02-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0003_organizationmember_is_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='member_fields_schema',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='is_master_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='member_fields',
            field=models.JSONField(null=True),
        ),
    ]
