# Generated by Django 4.0.1 on 2022-02-24 06:24

import apps.cycling_org.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0004_organization_member_fields_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='social_media',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.cycling_org.models.organization_logo_file_path_func),
        ),
    ]
