# Generated by Django 4.0.1 on 2022-02-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0006_organization_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationmember',
            old_name='is_valid',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='organizationmemberorg',
            old_name='is_valid',
            new_name='is_active',
        ),
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together={('organization', 'member', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationmemberorg',
            unique_together={('organization', 'top_organization', 'is_active')},
        ),
    ]
