# Generated by Django 4.0.1 on 2022-02-27 08:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0007_rename_is_valid_organizationmember_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=50, null=True, region=None),
        ),
    ]
