# Generated by Django 4.0.1 on 2022-03-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0011_member_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='status',
            field=models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('waiting', 'Waiting')], max_length=16, null=True),
        ),
    ]
