# Generated by Django 4.0.1 on 2022-03-06 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0014_organization_address_organization_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Height (m)'),
        ),
        migrations.AddField(
            model_name='member',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)], verbose_name='Weight (kg)'),
        ),
    ]
