# Generated by Django 4.0.1 on 2022-03-14 09:21

from django.db import migrations, models
import wrh_organization.helpers.fields_tracking


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0016_fieldstracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldstracking',
            name='changed_data',
            field=models.JSONField(blank=True, encoder=wrh_organization.helpers.fields_tracking.ExtendedJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='fieldstracking',
            name='fields_data',
            field=models.JSONField(blank=True, encoder=wrh_organization.helpers.fields_tracking.ExtendedJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='fieldstracking',
            name='refs_repr',
            field=models.JSONField(blank=True, encoder=wrh_organization.helpers.fields_tracking.ExtendedJSONEncoder, null=True),
        ),
    ]
