# Generated by Django 4.0.3 on 2022-04-11 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0019_race_create_by_race_create_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races', to='cycling_org.organization'),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_results', to='cycling_org.member'),
        ),
    ]
