# Generated by Django 4.0.3 on 2022-04-23 11:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usacycling', '0001_initial'),
        ('cycling_org', '0020_alter_race_organization_alter_raceresult_rider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='cycling_org.organization')),
            ],
            options={
                'unique_together': {('title', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='RaceSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('points_map', models.JSONField(null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(related_name='race_series', to='cycling_org.category')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('events', models.ManyToManyField(related_name='race_series', to='usacycling.usacevent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_series', to='cycling_org.organization')),
                ('races', models.ManyToManyField(related_name='race_series', to='cycling_org.race')),
            ],
            options={
                'unique_together': {('name', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='RaceSeriesResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('more_data', models.JSONField(null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycling_org.category')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cycling_org.organization')),
                ('race_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycling_org.raceseries')),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_series_results', to='cycling_org.member')),
            ],
            options={
                'unique_together': {('rider', 'race_series', 'organization')},
            },
        ),
    ]
