# Generated by Django 4.0.3 on 2022-06-14 16:06

from django.db import migrations, models
import django.db.models.deletion


# noinspection PyPep8Naming
def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    RaceSeries = apps.get_model("cycling_org", "RaceSeries")
    Race = apps.get_model("cycling_org", "Race")
    RaceSeries.objects.using(db_alias).all().delete()
    Race.objects.using(db_alias).all().delete()


# noinspection PyUnusedLocal
def reverse_func(apps, schema_editor):
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0022_member_more_data'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
