# Generated by Django 4.0.3 on 2022-06-18 07:44

from django.db import migrations, models
import rest_framework.utils.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0024_event_alter_race_event_alter_raceseries_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='more_data',
            field=models.JSONField(encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='more_data',
            field=models.JSONField(encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='more_data',
            field=models.JSONField(encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='member_fields',
            field=models.JSONField(encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='organizationmemberorg',
            name='member_fields',
            field=models.JSONField(encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='more_data',
            field=models.JSONField(encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='raceseriesresult',
            name='more_data',
            field=models.JSONField(encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
    ]
