# Generated by Django 4.0.3 on 2022-06-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0025_race_more_data_alter_event_more_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
