# Generated by Django 4.0.3 on 2022-06-18 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0026_alter_race_start_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceresult',
            name='place',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='raceseriesresult',
            name='place',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
