# Generated by Django 4.0.6 on 2022-09-29 13:31

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Event = apps.get_model("cycling_org", "Event")
    for event in Event.objects.using(db_alias).all():
        source = (event.more_data or {}).get('src')
        if not source:
            continue
        event.source = source
        event.save(update_fields=['source'])


# noinspection PyUnusedLocal
def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0033_event_logo_event_registration_website_event_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.CharField(editable=False, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='cycling_org.event'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
