# Generated by Django 4.0.6 on 2022-11-21 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cycling_org', '0035_alter_event_registration_website_alter_event_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('type', models.CharField(choices=[('withdraw', 'Withdraw'), ('org_register', 'Org Register')], max_length=16)),
                ('payment_id', models.CharField(max_length=64, verbose_name='Payment Id')),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
