# Generated by Django 4.0.6 on 2022-11-28 16:31

from django.db import migrations, models
import rest_framework.utils.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0038_alter_organization_membership_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='prefs',
            field=models.JSONField(editable=False, encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
    ]
