# Generated by Django 4.1.4 on 2023-01-15 09:10

from django.db import migrations, models
import rest_framework.utils.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0042_member_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='more_data',
            field=models.JSONField(blank=True, encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='prefs',
            field=models.JSONField(blank=True, editable=False, encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='more_data',
            field=models.JSONField(blank=True, encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='member_fields_schema',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='membership_plans',
            field=models.JSONField(blank=True, encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='prefs',
            field=models.JSONField(blank=True, editable=False, encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='signup_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='member_fields',
            field=models.JSONField(blank=True, encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='membership_plan',
            field=models.JSONField(blank=True, editable=False, encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='organizationmemberorg',
            name='member_fields',
            field=models.JSONField(blank=True, encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='more_data',
            field=models.JSONField(blank=True, encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='more_data',
            field=models.JSONField(blank=True, encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='raceseries',
            name='points_map',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raceseriesresult',
            name='more_data',
            field=models.JSONField(blank=True, encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
    ]
