# Generated by Django 4.1.4 on 2023-01-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0043_alter_event_more_data_alter_event_prefs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
