# Generated by Django 4.0.3 on 2022-06-25 13:25

from django.db import migrations, models
import rest_framework.utils.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='more_data',
            field=models.JSONField(encoder=rest_framework.utils.encoders.JSONEncoder, null=True, editable=False),
        ),
    ]
