# Generated by Django 4.0.6 on 2022-09-09 08:05

from django.db import migrations, models
import rest_framework.utils.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_more_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prefs',
            field=models.JSONField(editable=False, encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
    ]
