# Generated by Django 4.1.4 on 2022-12-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='draft',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
