# Generated by Django 4.0.1 on 2022-03-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usacycling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usacclub',
            name='club_aff_type',
            field=models.JSONField(null=True),
        ),
    ]
