# Generated by Django 4.0.1 on 2022-02-03 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other'), ('u', 'Unknown')], default='u', max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=50, null=True, region=None, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('address1', models.CharField(blank=True, max_length=256, null=True)),
                ('address2', models.CharField(blank=True, max_length=256, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('type', models.CharField(choices=[('regional', 'Regional'), ('team', 'Team'), ('advocacy_volunteer', 'Advocacy, Volunteer')], max_length=32)),
                ('social_media', models.JSONField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('signup_config', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMemberOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizaton_member_orgs', to='bycing_org.organization')),
                ('top_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_organizaton_member_orgs', to='bycing_org.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('membership_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bycing_org.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bycing_org.organization')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='member_orgs',
            field=models.ManyToManyField(related_name='organizations', through='bycing_org.OrganizationMemberOrg', to='bycing_org.Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(related_name='organizations', through='bycing_org.OrganizationMember', to='bycing_org.Member'),
        ),
    ]
