# Generated by Django 4.0.1 on 2022-02-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bycing_org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
