# Generated by Django 4.0.1 on 2022-02-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bycing_org', '0002_member_email_verified_member_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='is_valid',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationmemberorg',
            name='is_valid',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together={('organization', 'member', 'is_valid')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationmemberorg',
            unique_together={('organization', 'top_organization', 'is_valid')},
        ),
    ]
