# Generated by Django 4.0.1 on 2022-03-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bycing_org', '0008_alter_member_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together={('organization', 'member', 'is_active')},
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='exp_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='org_member_uid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together={('organization', 'org_member_uid', 'is_active'), ('organization', 'member', 'is_active')},
        ),
    ]
