# Generated by Django 4.0.1 on 2022-03-04 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bycing_org', '0012_organizationmember_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationmemberorg',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='organizationmemberorg',
            name='exp_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='organizationmemberorg',
            name='member_fields',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='organizationmemberorg',
            name='member_org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member_organizaton_member_orgs', to='bycing_org.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationmemberorg',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='organizationmemberorg',
            name='status',
            field=models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('waiting', 'Waiting')], max_length=16, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmemberorg',
            unique_together={('organization', 'member_org', 'is_active')},
        ),
        migrations.RemoveField(
            model_name='organizationmemberorg',
            name='top_organization',
        ),
    ]
