# Generated by Django 4.0.1 on 2022-04-07 13:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usacycling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bycing_org', '0017_alter_fieldstracking_changed_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('start_datetime', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usacycling.usacevent')),
            ],
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('more_data', models.JSONField(null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bycing_org.organization')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bycing_org.race')),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bycing_org.member')),
            ],
            options={
                'unique_together': {('rider', 'race', 'organization')},
            },
        ),
    ]
