# Generated by Django 4.0.3 on 2022-04-09 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usacycling', '0001_initial'),
        ('bycing_org', '0018_race_raceresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='race',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bycing_org.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='race',
            unique_together={('name', 'event', 'organization')},
        ),
    ]
