# Generated by Django 4.0.3 on 2022-06-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bycing_org', '0021_category_raceseries_raceseriesresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='more_data',
            field=models.JSONField(null=True),
        ),
    ]
