# Generated by Django 4.0.3 on 2022-07-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bycing_org', '0027_alter_raceresult_place_alter_raceseriesresult_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
