# Generated by Django 4.0.6 on 2022-07-11 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bycing_org', '0028_alter_category_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='raceseriesresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='raceseriesresult',
            name='race_result',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bycing_org.raceresult'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='raceseriesresult',
            unique_together={('race_series', 'race_result', 'category', 'organization')},
        ),
        migrations.RemoveField(
            model_name='raceseriesresult',
            name='rider',
        ),
    ]
