# Generated by Django 4.0.6 on 2022-09-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bycing_org', '0034_event_source_alter_race_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
