# Generated by Django 4.0.6 on 2022-11-26 07:23

from django.db import migrations, models
import rest_framework.utils.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('bycing_org', '0036_financialtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='membership_plans',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='membership_plan',
            field=models.JSONField(editable=False, encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
    ]
