# Generated by Django 4.0.6 on 2022-11-27 18:03

from django.db import migrations, models
import rest_framework.utils.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('bycing_org', '0037_organization_membership_plans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='membership_plans',
            field=models.JSONField(encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
    ]
