# Generated by Django 4.0.6 on 2022-11-29 09:24

from django.db import migrations, models
import rest_framework.utils.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('bycing_org', '0039_organization_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prefs',
            field=models.JSONField(editable=False, encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
    ]
